sonata_admin:
    title: 'Back-Office ALNJ'
    breadcrumbs:
        child_admin_route: edit
    dashboard:
        blocks:
            -
                position: left
                class: col-lg-6 fa-folder
                type: sonata.admin.block.admin_list
                settings:
                    groups: [fair]

        groups:
            fair:
                label: Kermesse
                items:
                    - admin.volunteer
                    - admin.stall
                    - admin.participation

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
